#Used to create the subscribers table

CREATE TABLE subscribers(
    subid INT PRIMARY KEY,
    package_type TEXT,
    num_weekly_services_utilized INT,
    preferred_genre TEXT,
    intended_use TEXT,
    weekly_consumption_hour REAL,
    num_ideal_streaming_services INT,
    age INT,
    male_TF INT,
    country TEXT,
    attribution_technical TEXT,
    attribution_survey TEXT,
    op_sys TEXT,
    months_per_bill_period INT,
    plan_type TEXT,
    monthly_price REAL,
    discount_price REAL,
    account_creation_date TEXT,
    trial_end_date TEXT,
    initial_credit_card_declined INT,
    join_fee REAL,
    language TEXT,
    payment_type TEXT,
    num_trial_days INT,
    current_sub_TF INT,
    payment_period INT,
    last_payment TEXT,
    next_payment TEXT,
    cancel_date TEXT,
    trial_completed INT
);
